#
# Tap dat
#
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'inviqa/tools'

#
# Brews
#
brew 'pkg-config'
brew 'libyaml'
brew 'openssl'
brew 'ansible'
brew 'docbook'
brew 'asciidoc'
brew 'autoconf'
brew 'boost'
brew 'cmake'
brew 'dnsmasq'
brew 'git'
brew 'gnupg'
brew 'go'
brew 'keybase'
brew 'libgpg-error'
brew 'libassuan'
brew 'pinentry'
brew 'lastpass-cli', args: ['with-doc', 'with-pinentry']
brew 'mailhog'
brew 'mysql'
brew 'ruby-build'
brew 'rbenv'
brew 'wget'

#
# Casks
#
cask 'adium'
cask 'adobe-reader'
cask 'alfred'
cask 'atom'
cask 'charles'
cask 'chefdk'
cask 'dash'
cask 'firefox'
cask 'fluid'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'hem'
cask 'iterm2'
cask 'java6'
cask 'lastpass'
cask 'licecap'
cask 'macdown'
cask 'ngrok'
cask 'opera'
cask 'phpstorm'
cask 'rdm'
cask 'sequel-pro'
cask 'skype'
cask 'slack'
cask 'sonos'
cask 'spectacle'
cask 'spotify'
cask 'staruml'
cask 'sublime-text'
cask 'thyme'
cask 'toggldesktop'
cask 'transmission'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'vlc'
